# Used in specs
[accounts.protoss.fenix]
access_key = "fenix"
secret = "zealot!"

[accounts.protoss.fenix.bastion]
staging = "staging.bastion.example.com"
production = "prod.bastion.example.com"

[accounts.protoss.tassadar]
access_key = "tassadar"
secret = "lightning!"

[accounts.terran.raynor]
access_key = "raynor"
secret = "abcd1234"
